### ISSUE TITLE
duplicated results in `wbsearch`

### ISSUE THREAD

**Issue by vincentarelbundock** [nset-ornl/wbstats#14]
I get some duplicated results when I search using a simple regex.

``` r
library(wbstats)
a <- wbsearch('gdp.*capita')
a <- duplicated(a$indicatorID)
sum(a)
#> [1] 15
```

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jpiburn** [comment]
Thank you for finding that. `wbsearch()` still had this issue, but has been deprecated in version 1.0. its replacement, `wb_search()` works correctly.

``` r
library(wbstats)

b <- wb_search('gdp.*capita')
b <- duplicated(b$indicator_id)

sum(b)
#> [1] 0
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
