### ISSUE TITLE
Downloading data with wb_data()

### ISSUE THREAD

**Issue by denironyx** [nset-ornl/wbstats#19]
Hi @jpiburn, I noticed that the `wb_data()` function is no longer available in the current version of the `wbstats` package. 

However, I have been exploring other functions in the `wbstats` package and none is currently performing the same function as the `wb_data()` function.

So, is there a reason why the `wbstats` package no longer supports the `wb_data()` function?

**Comment by greg-minshall** [comment]
@denironyx i install_git() from the [repository](https://github.com/nset-ornl/wbstats) and i seem to have the `wb_data()` function (and use it in my code).  in case that helps.

**Comment by denironyx** [comment]
Hi @greg-minshall, did you install the `wbstats` package directly from GitHub or CRAN?? It seems the `wb_data()` function is no longer supported in the latest version of the package.

**Comment by greg-minshall** [comment]
hi, @denironyx -- yes, i installed via github (see below).  there's always a time lag before things show up on CRAN, though how long, etc., are beyond my ken.

```
devtools::install_github("nset-ornl/wbstats", force=TRUE)
```

hope that helps -- good luck!
