### ISSUE TITLE
Error in getting data

### ISSUE THREAD

**Issue by msgoussi** [nset-ornl/wbstats#22]
wbstats::wb(indicator = "SH.XPD.PVTD.CH.ZS", 
            startdate = 2014, enddate = 2019,
            removeNA = TRUE)

Error in wbstats::wb(indicator = "SH.XPD.PVTD.CH.ZS", startdate = 2014,  : 
  indicator parameter has no valid values. Please check documentation for valid inputs

**Comment by jpiburn** [comment]
Hi, this looks to be an issue with an out of date `wb_cachelist`. When upgrading to the latest CRAN release version, this issue should be resolved.
