### ISSUE TITLE
disappeared from CRAN?

### ISSUE THREAD

**Issue by greg-minshall** [nset-ornl/wbstats#27]
hi.  [CRAN](https://cran.r-project.org/web/packages/wbstats/index.html) says
````
Package ‘wbstats’ was removed from the CRAN repository.
````

cheers.

**Comment by jpiburn** [comment]
Hi,

Yes, sorry it was temporarily taken down as I wasn't quick enough in responding to a couple issues that the CRAN maintainers wanted me to address.

It should be back up soon. Sorry for any inconveniences. I'll update this issue when it's back up

**Comment by jpiburn** [comment]
Just providing a status update. The issue was fixed about a week ago and I resubmitted to CRAN. Haven't heard back from them yet, but I will reach out to them again in the next couple days.

**Comment by jpiburn** [comment]
Sorry for the delay, but `v1.0.4` is now back up on CRAN 🎉 . Again sorry for it being temporally pulled down and the delay in getting it back up.

**Comment by greg-minshall** [comment]
````
-wbstats,https://github.com/nset-ornl/wbstats
+wbstats,cran
````

hooray!

**Comment by joachim-gassen** [comment]
Just wanted to say thanks as well. I use {wbsats} for several projects (e.g., [tidycovid19](https://github.com/joachim-gassen/tidycovid19) and [ExPanDaR](https://github.com/joachim-gassen/ExPanDaR)) and it is great to see it back on CRAN. Thank you for all your work on maintaining this super useful package!
