### ISSUE TITLE
provide fixed=TRUE in wbsearch

### ISSUE THREAD

**Issue by Stefan2015-5** [nset-ornl/wbstats#9]
sometimes you now the indicators name but it contains reg exp character strings. It would be good to disable reg ex interpretation of the pattern argument in wbsearch.

`indicator<-   "Households and NPISHs final consumption expenditure (% of GDP)"`
`a<- wbsearch(indicator)`
`In wbsearch(indicator) :`
`  no matches were found for the search term Households and NPISHs final consumption expenditure (% of GDP). Returning an empty data frame`

But of course there is one ("NE.CON.PRVT.ZS").
something like `a<- wbsearch(indicator, fixed=TRUE)` like in the `grep` case is needed.

Best, 
Stefan

PS: Great package!!

**Comment by jpiburn** [comment]
Thanks for the suggestion! Good catch. I'll look into incorporating that as soon as possible.

**Comment by jpiburn** [comment]
Hard to say 2 years is as soon as possible.... sorry about that. but in  version `1.0` (not on cran yet, but on github), the function `wb_search()` now passing `...` to the `grep()` so you can now pass any additional arguments that grep accepts
